### ISSUE TITLE
Rebuilding native modules breaks the asar module.

### ISSUE THREAD

**Issue by simtel12** [atom/grunt-download-atom-shell#25]
It appears that grunt-download-atom-shell is not compatible with any project that uses asar [ asar, grunt-asar, etc].

After native modules have been built by the ```download-atom-shell``` task, any calls to the asar module will fail with "Warning: Module version mismatch. Expected 14, got 43. Use --force to continue."

This is a persistent error - asar must be reinstalled in order to work again.

Example files that can be used to demonstrate this:
Gruntfile.js: http://pastebin.com/RxgXFXhY
package.json: http://pastebin.com/UCyXEvD1

Use those, run ```npm install``` to get the modules installed, and then ```grunt -v``` - you should see the above error.

This appears related to apm rebuilding the version of chromium-pickle that asar uses, but I'm at a loss for workarounds.

**Comment by paulcbetts** [comment]
Atom works around this by putting its build modules in a separate folder (i.e. `build/node_modules` for all the grunt tasks, `node_modules` for what goes in the app). This also has the benefit of not ending up shipping Grunt tasks in your packaged binary

**Comment by simtel12** [comment]
In our setup, 'asar' is simply a packaging setup and should not go into the final binary either.  In fact, I had wanted to use the 'grunt-asar' task, but that suffers from the same problem.

I suppose I could separate that 'build/download' step from the 'build/package' step in the directory structure and use something like the ```command``` module to execute them...

What does the rebuilding of the modules vs the latest chromium provide?  Does it make sense to only rebuild the dependencies, and not the devDependencies?

**Comment by paulcbetts** [comment]
> What does the rebuilding of the modules vs the latest chromium provide?

It makes the modules loadable in Electron, otherwise you'd get the same error you're seeing now, only backwards

**Comment by parasyte** [comment]
I have experienced this issue with `grunt-asar`.

* https://github.com/melonjs/boilerplate/blob/c60c893b4842fa02a9bef2a0cb3f33ef271073d8/Gruntfile.js#L138
* https://github.com/melonjs/boilerplate/blob/02e324276d7ae8819d061f01d34925177baa7f3c/package.json

The dependencies in package.json are all build dependencies (there are no app dependencies). So I don't understand how to apply the recommendation to separate build modules from app modules in this case. My `asar` task simply creates the archive in the appropriate Electron directory.

Any other tips?

**Comment by parasyte** [comment]
A workaround for me is setting the `rebuild: false` task option. Of course, this will cause native app dependencies to install correctly...
