### ISSUE TITLE
Unable to download atom-shell releases.

### ISSUE THREAD

**Issue by simtel12** [atom/grunt-download-atom-shell#27]
Master branch is only able to download 'electron' releases, this makes it unable to download atom-shell v0.23 and older.

#24 is an attempt to fix it, but perhaps there's a better way.

**Comment by kevinsawicki** [comment]
I made a tweak in https://github.com/atom/grunt-download-atom-shell/commit/41248d7cce80fc318cfc00c6a8f5b2a588af83a8 for this. It just looks for assets with `atom-shell` in the release.

Do you think that is sufficient?

**Comment by simtel12** [comment]
It probably is.  That said, I'm a fan of making big rename changes as obvious as possible, since it tends to break other scripts too; which is why in my pull request for the rename, I created a new task and made it incompatible with the older versions'

This gets the job done though, and at the end of the day that is the most important thing.  :+1:

**Comment by kevinsawicki** [comment]
> That said, I'm a fan of making big rename changes as obvious as possible

Yeah, I was planning on renaming both the package and task, but `grunt-download-electron` was already taken and I was reaching out to the author.

**Comment by kevinsawicki** [comment]
> Yeah, I was planning on renaming both the package and task, but grunt-download-electron was already taken and I was reaching out to the author.

The repository and task have now been renamed and published as 2.0.0
